# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
name: Deploy
on:
#  workflow_run:
 #   workflows: ["CI"]
  #  branches: [main]
   # types: 
    #  - completed
      pull_request:
            types: [closed]
            branches: 
              - master

jobs:
  Docker-Image-and-SSH-Deployment:
    runs-on: ubuntu-latest

    steps:
      # https://github.com/marketplace/actions/build-and-push-docker-images
      - name: Set up DockerHub QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: felixsteinke/private:BusinessDice-Server
          
      - name: Image digest output
        run: echo ${{ steps.docker_build.outputs.digest }}
        
      - name: SSH Deploy
        uses: fifsky/ssh-action@master
        with:
          command: |
            echo "[INFO] Stop running container:"
            sudo docker kill business-dice-server
            echo "[INFO] Delete old container:"
            sudo docker rm business-dice-server
            echo "[INFO] Pull new image:"
            sudo docker pull felixsteinke/private:BusinessDice-Server
            echo "[INFO] Run new image:"
            sudo docker run -d --name business-dice-server -p 443:8080 felixsteinke/private:BusinessDice-Server # start container in background on host port 443
          host: ${{ secrets.BW_CLOUD_IP }}
          user: ${{ secrets.BW_CLOUD_USER }}
          key: ${{ secrets.BW_CLOUD_PRIVATE_KEY}}
